name: Code Health Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Code Health Check
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Prettier Check
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier
      - name: ESLint Check
        uses: borales/actions-yarn@v4
        with:
          cmd: eslint
      - name: Build Check
        uses: borales/actions-yarn@v4
        with:
          cmd: build-test
      - name: Jest Test Check
        uses: borales/actions-yarn@v4
        with:
          cmd: test
